### ISSUE TITLE
Misplaced DOCTYPE declaration

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev.github.io#130]
Latests CI tests are showing lots of `Misplaced DOCTYPE declaration`. I think at least two of these pages are redirects created by the `jekyll-redirect-from` plugin, so something may be broken with that plugin.

```
- ./contributing/index.html
  *  Misplaced DOCTYPE declaration (line 175)
- ./docs/kernel-hackers-notebook/ev3-adc/index.html
  *  External link http://www.lm-sensors.org/ failed: got a time out (response code 0)
- ./docs/tutorials/writing-sd-card-image-mac-command-line/index.html
  *  Misplaced DOCTYPE declaration (line 175)
- ./issues/index.html
  *  Misplaced DOCTYPE declaration (line 175)
- ./news/2015/07/08/Kernel-Release-v3.16.7-ckt11-5-ev3dev-ev3.html
  *  Misplaced DOCTYPE declaration (line 175)
- ./news/2015/07/08/ev3-ev3dev-jessie-2015-07-08-release/index.html
  *  internally linking to /news/2015/07/08/Kernel-Release-v3.16.7-ckt11-5-ev3dev-ev3, which does not exist (line 195)
```

**Comment by WasabiFan** [comment]
I can't figure out what is happening here... html-proofer doesn't mention doctypes at all based on a search of their source code, so I would expect that it's a dependency of that library, but I checked their HTML parser and it doesn't do anything like this either. So I'll keep looking.

Additionally, all the DOCTYPE errors are coming from the same line number -- 175 -- even though the files it is referencing are only a few lines long. So I don't know what is going on there either.

And naturally, searching for these errors online returns this issue as the first result, so that isn't too helpful either :wink:
