### ISSUE TITLE
Limit item count in news rss/atom feed

### ISSUE THREAD

**Issue by dlech** [ev3dev/ev3dev.github.io#191]
I'm not sure what triggered it, but my rss reader decided that all of our news articles were new, which was 41. Most rss feeds are limited to the 10 most recent articles. This would also be nice for new subscribers.

**Comment by dlech** [comment]
GitHub Pages has built in support for rss feeds now: https://help.github.com/articles/atom-rss-feeds-for-github-pages/

so while we are at it, we might convert to the built-in version instead.

**Comment by WasabiFan** [comment]
Limiting the number of articles to 10 seems reasonable.

Although I can't remember what it was, last time I looked at the RSS plugin for Jekyll, there was something that gave me the impression that we shouldn't use it (I'm not sure if it was an issue with the work required or functionality). It's still worth looking into to see if it suits our needs, though.

Limiting the number of articles should in theory be possible by adding an `if` in the loop:

```
{% if forloop.index > 10 %}
    {% break %}
{% endif %}
```

I'll open a PR if it hasn't already been done in a bit.

**Comment by WasabiFan** [comment]
Interestingly, in my local preview, the atom feed's contents are markdown instead of HTML, which is different from how they are on the public site. I am not sure why this is the case.

Also, it turns out that Jekyll provides the ability to [manually set the excerpt separator](https://jekyllrb.com/docs/posts/#post-excerpts); this means that we could set the separator to a comment in the news posts and adjust the excerpt to be something of appropriate length in each post. If we then used those excerpts on the news index page, we wouldn't have to deal with the odd splitting. This isn't necessarily something we should do, but it is an option if we run into more issues with those index page previews.

**Comment by dlech** [comment]
BTW, I really like this `excerpt_separator` thing. I have started using it in news posts.

**Comment by WasabiFan** [comment]
![image](https://cloud.githubusercontent.com/assets/3310349/17450922/f7962600-5b17-11e6-81f1-1c38e452f053.png)

We may want to add those separators to other pages as well :laughing: Or maybe do something else to make each text block longer. I think the Docker one with the separator added looks very good, though.

**Comment by dlech** [comment]
My plan is to make new news posts look good and not worry about the old ones. In a few months it won't matter much anymore.

**Comment by WasabiFan** [comment]
OK, sounds good. The archive page is ugly anyway :laughing:
