### ISSUE TITLE
Remove "calling it a day" section

### ISSUE THREAD

**Issue by WasabiFan** [ev3dev/ev3dev.github.io#250]
I think this breaks the flow of the Getting Started guide. This content is valuable, so we may want to break it out into its own page, but the last step in the guide should lead into something about writing code without any barriers in between.

From ev3dev/ev3dev#734.

**Comment by ndward** [comment]
I think the bigger problem on the Getting Started page is that there is no section called 'Choose a Programming Language'. There is a section called 'Do something awesome' which is actually about choosing a programming language but 'do something awesome' surely refers to writing awesome programs rather than choosing a language. So I would suggest either that that section should be renamed  'Choose a Programming Language' and followed by a new paragraph with a title like 'Write and run awesome programs', or, if there is nothing to be said about writing and running programs, then the existing step 6 could be renamed: 'Choose a programming language and do something awesome'.

**Comment by WasabiFan** [comment]
Good idea. Thanks for commenting on the related issue! I'll make that change along with removing the other section.
