### ISSUE TITLE
Download section

### ISSUE THREAD

**Issue by vini2710** [ev3dev/ev3dev.github.io#253]
It would be really nice to have a downloads page with a link to the nightly builds (which are hosted [here](https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/)).

The latest build for the ev3 was almost 10 months ago...

**Comment by WasabiFan** [comment]
The Getting Started page has a link to the nightlies, although it isn't very obvious. Either way, I don't think this is a problem because we expect to release a new official image very soon (next couple days).

The reason that we don't have a separate downloads page is because we want to make sure that new users go through the Getting Started guide before attempting to download anything. The worry is that a new user will download an image and then have no idea what to do with it.

**Comment by vini2710** [comment]
OK, I get your point... It is awesome that you are releasing a new image!

**Comment by WasabiFan** [comment]
Yeah I'm pretty excited too! Thanks for asking about this; if you have any other feedback, feel free to open issues for it.

**Comment by vini2710** [comment]
Actually I just got an idea... Maybe you could host the nightly image builds with the stable builds on github (assuming you consider them finished and stable)?

**Comment by WasabiFan** [comment]
The idea with the nightlies is that they are just snapshots of our codebase, so they aren't intended for use by most users. As we haven't released an official image in a while, we have been violating that a bit because we are confident in the state of those builds right now, but in general we don't expect that to be the case in the future. We want the official image releases to be the first things listed on the "releases" page.

**Comment by vini2710** [comment]
Sounds good if you are planning to release official builds more often. I guess that is the best option for the average user and for beginners.
