### ISSUE TITLE
"Getting Started" says "2GB or large" but actual download image is 3.8GB

### ISSUE THREAD

**Issue by davidlgj** [ev3dev/ev3dev.github.io#350]
Hi,

I might have missed a download but "Getting Started"[1] has the sentence "A microSD or microSDHC card (2GB or larger)." in the top list, but the downloaded image for ev3 is currently about 3.8GB.

cheers

[1] http://www.ev3dev.org/docs/getting-started/

**Comment by WasabiFan** [comment]
Thanks for the report! It turns out that we only realized this a couple hours ago (see https://github.com/ev3dev/ev3dev/issues/850) after a discussion via chat with someone having a size issue. The expected size _is_ 1.8GB, and the problem is that this particular image is full of empty space. I suspect that the image size won't be fixed until the next release, but in the mean time if you need to be able to flash to a smaller card you should be able to use [this snapshot build](https://oss.jfrog.org/list/oss-snapshot-local/org/ev3dev/brickstrap/2017-02-08/snapshot-ev3dev-jessie-ev3-generic-2017-02-08.img.xz). It should be mostly the same as the current official image release, but it is the intended size. If you're using a card that is 4GB+, you can continue with the normal image and it should be OK.

@dlech Do you think we should temporarily change the minimum size listed here with a note about this problem?

**Comment by davidlgj** [comment]
Wow, just bad timing for me then :D 

Thanks for the quick reply, dowloading the snapshot image now. I only have a spare 2GB card so you saved my weekend!

Wonderful project btw.

**Comment by dlech** [comment]
I'll redo the image in a couple days.

**Comment by dlech** [comment]
Done
